Project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('teacher.urls')),
    path('student/',include('student.urls')),
    path('admin-module/',include('admin_module.urls')),
    path('timetable/',include('timetable.urls')),
]

timetable/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('create-subject/',views.create_subject,name='create-subject'),
    path('create-lab/',views.create_lab,name='create-lab'),
    path('create-class/',views.create_class,name='create-class'),
    path('view-classes/',views.view_classes,name='view-classes'),
    path('edit-class/<int:class_id>/',views.edit_class,name='edit-class'),
    path('delete-class/<int:class_id>/', views.delete_class, name='delete-class'),

    path('generate-timetable/',views.generate_timetable_view,name='generate-timetable'),
    path('display-timetable/',views.display_timetable,name='display-timetable'),
    
]

timetable/models.py
from django.db import models

class Subject(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Lab(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Class(models.Model):
    class_name = models.CharField(max_length=10)
    subjects = models.ManyToManyField(Subject)
    labs = models.ManyToManyField(Lab)

    def __str__(self):
        return self.class_name
    

class TimetableEntry(models.Model):
    class_name = models.ForeignKey(Class, on_delete=models.CASCADE)
    day = models.CharField(max_length=20)  
    time = models.CharField(max_length=20) 
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True, blank=True)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        if self.subject:
            subject_str = self.subject
        else:
            subject_str = "No Subject"
        
        if self.lab:
            lab_str = self.lab
        else:
            lab_str = "No Lab"
    
        return f'{self.class_name} - {self.day} - {self.time} - {self.subject} - {self.lab}'

timetable/forms.py
from django import forms
from .models import Class, Subject,Lab


class ClassForm(forms.ModelForm):
    class Meta:
        model = Class  # Specify the model attribute
        fields = ['class_name', 'subjects', 'labs'] 

    subjects = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )
    
    labs = forms.ModelMultipleChoiceField(
        queryset=Lab.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )
# class ClassForm(forms.ModelForm):
#     subjects = forms.ModelMultipleChoiceField(
#         queryset=Subject.objects.all(),
#         widget=forms.CheckboxSelectMultiple
#     )
    
#     labs = forms.ModelMultipleChoiceField(
#         queryset=Lab.objects.all(),
#         widget=forms.CheckboxSelectMultiple
#     )
# class ClassForm(forms.ModelForm):
#     subjects = forms.ModelMultipleChoiceField(
#         queryset=Subject.objects.all(),
#         widget=forms.CheckboxSelectMultiple
#     )
    
#     labs = forms.ModelMultipleChoiceField(
#         queryset=Lab.objects.all(),
#         widget=forms.CheckboxSelectMultiple,
#         required=False  # Make labs field optional
#     )
#     class Meta:
#         model = Class
#         fields = ['class_name', 'subjects','labs']



class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['name']


class LabForm(forms.ModelForm):
    class Meta:
        model = Lab
        fields = ['name']


class TimetableGenerateForm(forms.Form):
    confirm_generation = forms.BooleanField(
        label='I confirm that I want to generate the timetable',
        required=True,
    )
    selected_class = forms.ModelChoiceField(
        label='Select Class',
        queryset=Class.objects.all(),
        empty_label=None,
    )

timetable/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from .forms import ClassForm,SubjectForm, TimetableGenerateForm,LabForm
from .models import Class,TimetableEntry
from .generate_timetable import generate_timetable
from django.http import JsonResponse
from django.contrib import messages


@user_passes_test(lambda u: u.is_superuser)
def create_subject(request):
    if request.method == 'POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin-dashboard')
    else:
        form = SubjectForm()

    return render(request, 'timetable/create_subject.html', {'form': form})


@user_passes_test(lambda u: u.is_superuser)
def create_lab(request):
    if request.method == 'POST':
        form = LabForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin-dashboard')
    else:
        form = LabForm()

    return render(request, 'timetable/create_lab.html', {'form': form})


@user_passes_test(lambda u: u.is_superuser)
def create_class(request):
    if request.method == 'POST':
        form = ClassForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin-dashboard')  
    else:
        form = ClassForm()

    return render(request, 'timetable/create_class.html', {'form': form})


@user_passes_test(lambda u: u.is_superuser)
def view_classes(request):
    classes = Class.objects.all()
    return render(request, 'timetable/view_classes.html', {'classes': classes})


@user_passes_test(lambda u: u.is_superuser)
def edit_class(request, class_id):
    instance = get_object_or_404(Class, id=class_id)
    
    if request.method == 'POST':
        form = ClassForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('view-classes') 
    else:
        form = ClassForm(instance=instance)

    return render(request, 'timetable/edit_class.html', {'form': form})



# @user_passes_test(lambda u: u.is_superuser)
# def delete_class(request, class_id):
#     class_instance = get_object_or_404(Class, id=class_id)
    
#     if request.method == 'POST':
#         class_instance.delete()
#         return JsonResponse({'message': 'Class deleted successfully'})

#     return render(request, 'timetable/view_classes.html', {'class_instance': class_instance})

from django.http import JsonResponse

@user_passes_test(lambda u: u.is_superuser)
def delete_class(request, class_id):
    class_instance = get_object_or_404(Class, id=class_id)
    
    class_instance.delete()
    return JsonResponse({'message': 'Class deleted successfully'})


@user_passes_test(lambda u: u.is_superuser)
def generate_timetable_view(request):
    if request.method == 'POST':
        form = TimetableGenerateForm(request.POST)
        if form.is_valid() and form.cleaned_data['confirm_generation']:
            selected_class = form.cleaned_data['selected_class']
            generate_timetable(selected_class)
            return redirect('display-timetable')
    else:
        form = TimetableGenerateForm()

    context = {'form': form}
    return render(request, 'timetable/generate_timetable.html', context)

# @user_passes_test(lambda u: u.is_superuser)
# def generate_timetable_view(request):
#     if request.method == 'POST':
#         form = TimetableGenerateForm(request.POST)
#         if form.is_valid():
#             if form.cleaned_data.get('confirm_generation', False):
#                 selected_class = form.cleaned_data.get('selected_class')
#                 if selected_class is not None:
#                     generate_timetable(selected_class)
#                     return redirect('display-timetable')
#                 else:
#                     # Handle the case where selected_class is None
#                     # This might occur if the form submission is tampered with
#                     # or if there's an issue with the form rendering
#                     messages.error(request, "Invalid selected class.")
#             else:
#                 # Handle the case where confirm_generation is False
#                 messages.warning(request, "Generation not confirmed.")
#         else:
#             # Handle the case where form validation fails
#             messages.error(request, "Form validation failed.")
#     else:
#         form = TimetableGenerateForm()

#     context = {'form': form}
#     return render(request, 'timetable/generate_timetable.html', context)




# def display_timetable(request):
#     user = request.user
#     if hasattr(user, 'teacher'):
#         timetable_entries = TimetableEntry.objects.filter(subject=user.teacher.subject_taught1)
#         timetable_entries = TimetableEntry.objects.filter(subject=user.teacher.subject_taught2)
        
#     elif hasattr(user, 'student'):
#         timetable_entries = TimetableEntry.objects.filter(class_name=user.student.class_name)
#     else:
#         timetable_entries = TimetableEntry.objects.all()

    
#     timetable_by_class = {}
#     for entry in timetable_entries:
#         if entry.class_name not in timetable_by_class:
#             timetable_by_class[entry.class_name] = []
#         timetable_by_class[entry.class_name].append(entry)

#     context = {'timetable_by_class': timetable_by_class}
#     return render(request, 'timetable/display_timetable.html', context)
def display_timetable(request):
    user = request.user
    if hasattr(user, 'teacher'):
        subject1_timetable_entries = TimetableEntry.objects.filter(subject=user.teacher.subject_taught1)
        subject2_timetable_entries = TimetableEntry.objects.filter(subject=user.teacher.subject_taught2)
        timetable_entries = subject1_timetable_entries.union(subject2_timetable_entries)
        
    elif hasattr(user, 'student'):
        timetable_entries = TimetableEntry.objects.filter(class_name=user.student.class_name)
    else:
        timetable_entries = TimetableEntry.objects.all()

    timetable_by_class = {}
    for entry in timetable_entries:
        if entry.class_name not in timetable_by_class:
            timetable_by_class[entry.class_name] = []
        timetable_by_class[entry.class_name].append(entry)

    context = {'timetable_by_class': timetable_by_class}
    return render(request, 'timetable/display_timetable.html', context)

templates/timetable/create_class.html
{%extends "admin_module/admin_dashboard.html"%}
{%load static%}
{%block content%}

<div class="container col-md-6 p-5 mt-5" >
  <div class="row p-5 mt-5" style="box-shadow: #0e248559 0px 5px 15px;">

      <form method="post">
        {% csrf_token %}
        {{ form.as_p}} 
        <button type="submit" class="btn btn-primary">Create Class</button>
    </form>
  </div>
</div>    
{%endblock%} 
{%comment%}
{% extends "admin_module/admin_dashboard.html" %}
{% load static %}

{% block content %}
<div class="container col-md-6 p-5 mt-5">
  <div class="row p-5 mt-5" style="box-shadow: #0e248559 0px 5px 15px;">
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_subjects">Subjects:</label>
        {{ form.subjects }}
      </div>
      <div class="form-group">
        <label for="id_labs">Labs:</label>
        {{ form.labs }}
      </div>
      <button type="submit" class="btn btn-primary">Create Class</button>
    </form>
  </div>
</div>
{% endblock %}
{%endcomment%}

templates/timetable/create_lab.html
{%extends "admin_module/admin_dashboard.html"%}
{%load static%}
{%block content%}

<div class="container col-md-6 mx-auto mt-5 p-5">
  <div class="row p-5 mt-5" style="box-shadow: rgba(14, 36, 133, 0.35) 0px 5px 15px;">
      <form method="post">
        {% csrf_token %}
        
        {{ form.as_p }}
     
        <button type="submit" class="btn btn-primary">Create Lab</button>
    </form>
  </div>  
</div>
{%endblock%}

templates/timetable/create_subject.html
{%extends "admin_module/admin_dashboard.html"%}
{%load static%}
{%block content%}

<div class="container col-md-6 mx-auto mt-5 p-5">
  <div class="row p-5 mt-5" style="box-shadow: rgba(14, 36, 133, 0.35) 0px 5px 15px;">
      <form method="post">
        {% csrf_token %}
        
        {{ form.as_p }}
     
        <button type="submit" class="btn btn-primary">Create Subject</button>
    </form>
  </div>  
</div>
{%endblock%}

templates/timetable/display_timetable.html
{% extends "admin_module/admin_dashboard.html" %}
{% load static %}

{% block content %}
<div class="container" style="margin-top: 100px;">

    {% for class_name, timetable_entries in timetable_by_class.items %}
    <h2>Timetable for {{ class_name }}</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Day</th>
                <th>Time</th>
                <th>Subject</th>
                <th>Lab</th>
            </tr>
        </thead>
        <tbody>
            {% for entry in timetable_entries %}
                <tr>
                    <td>{{ entry.day }}</td>
                    <td>{{ entry.time }}</td>
                    <td>
                        {% if entry.subject %}
                            {{ entry.subject.name }}
                        {% else %}
                            No Subject 
                        {% endif %}
                    </td>
                    <td>
                        {% if entry.lab %}
                            {{ entry.lab.name }} 
                        {% else %}
                            No Lab 
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endfor %}






</div>
{% endblock %}

templates/timetable/edit_class.html
{%extends "admin_module/admin_dashboard.html"%}
{%load static%}
{%block content%}
<div class="container col-md-6 mx-auto mt-5 p-5 ">
  <h2>Edit Subjects</h2>
  
  <div class="row p-5 mt-5" style="box-shadow: rgba(14, 36, 133, 0.35) 0px 5px 15px;">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Update Class</button>
    </form>
</div>
</div>
{%endblock%}

templates/timetable/generate_timetable.html
{%extends "admin_module/admin_dashboard.html"%}
{%load static%}
{%block content%}


<div class="container col-md-6 mx-auto mt-5 p-5 ">
  <h2>Generate Timetable</h2>
  
  <div class="row p-5 mt-5" style="box-shadow: rgba(14, 36, 133, 0.35) 0px 5px 15px;">

      
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Generate Timetable</button>
    </form>

</div>

</div>    
{%endblock%}
  

templates/timetable/view_classes.html
{% extends "admin_module/admin_dashboard.html" %}
{% load static %}

{% block content %}
<div class="container col-md-6 mx-auto mt-5 p-5 ">
  <h2>Available Classes</h2>
  <div class="row p-5 mt-5" style="box-shadow: rgba(14, 36, 133, 0.35) 0px 5px 15px;">
    
    <div class="container">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Class Name</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for class_instance in classes %}
            <tr>
              <td>{{ class_instance.class_name }}</td>
              <td>
                <a href="{% url 'edit-class' class_instance.id %}" class="btn btn-secondary">Edit</a>
                <a href="#" class="btn btn-danger" onclick="confirmDelete('{{ class_instance.class_name }}', '{{ class_instance.id }}')">Delete</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
  function confirmDelete(className, classId) {
    var confirmDelete = confirm("Are you sure you want to delete " + className + "?");
    if (confirmDelete) {
      // Send a POST request to delete the class
      fetch("{% url 'delete-class' class_id=0 %}".replace('0', classId), {
        method: 'POST',
        headers: {
          'X-CSRFToken': '{{ csrf_token }}',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          class_id: classId
        })
      }).then(response => {
        if (response.ok) {
          // Reload the page after successful deletion
          window.location.reload();
        } else {
          alert('Failed to delete class');
        }
      }).catch(error => {
        console.error('Error deleting class:', error);
      });
    }
  }
</script>

{% endblock %}

{%comment%}
{%extends "admin_module/admin_dashboard.html"%}
{%load static%}
{%block content%}

<div class="container col-md-6 mx-auto mt-5 p-5 ">
  <h2>Available Classes</h2>
  <div class="row p-5 mt-5" style="box-shadow: rgba(14, 36, 133, 0.35) 0px 5px 15px;">

    
    <div class="container">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Class Name</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for class in classes %}
            <tr>
              <td>{{ class.class_name }}</td>
              <td>
                <a href="{% url 'edit-class' class.id %}" class="btn btn-secondary">Edit</a>
                <a href="#" class="btn btn-danger" onclick="confirmDelete('{{ class.class_name}}', '{{ class.id  }}')">Delete</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

    </div>

    <script>
      function confirmDelete( className,classId) {
        var confirmDelete = confirm("Are you sure you want to delete " + className + "?");
        if (confirmDelete) {
         
          window.location.href = "{% url 'delete-class' class_id=0 %}".replace('0', classId);
        }
      }
    </script>


  


  {%endblock%}
 {%endcomment%} 